<CsoundSynthesizer>
<CsInstruments>
sr = 48000
ksmps = 32
nchnls = 1
0dbfs = 1

; Explosions
; Noise generated by spline interpolation through random points.
; p4: attack time (s)
; p5: minimum spline point frequency
; p6: maximum spline point frequencyy

instr 1
	k1 linseg 0, p4, 1, p3 - p4, 0
	k2 linseg p5, p4, p6, p3 - p4, p5
	a1 rspline -k1, k1, p5, k2
	out a1
endin
</CsInstruments>
<CsScore>
i 1 0 2 0.01 100 20000
e
</CsScore>
</CsoundSynthesizer>

